### ISSUE TITLE
Deploy Kibana Dashboards in airship-core/multi-tenant types

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#150]
**Proposed change**
Provide a demonstration of a Kibana dashboard that includes logs from elasticsearch as part of an airship-core and multi-tenant site deployment.

MVP requirements:
1.	Functioning lma-stack composite
- 	Create LMA-stack composite in airshipit/treasuremap · Issue #61 · airshipit/treasuremap (github.com)
2.	Functioning elastic-stack composite
-	Create airshipit/treasuremap Function for Elasticsearch · Issue #52 · airshipit/treasuremap (github.com)
-	Includes basic pod / system logs 
-	All composite overrides
3.	Elasticsearch function
-	Create airshipit/treasuremap Function for Elasticsearch · Issue #52 · airshipit/treasuremap (github.com)
4.	Kibana Function
-	Create airshipit/treasuremap Function for Kibana · Issue #53 · airshipit/treasuremap (github.com)
-	Dashboard is accessible via nodeport
-	Dashboard showcases data from Elasticsearch

**Comment by StevTheDev** [comment]
Hey @lb4368, please assign this one to me!

**Comment by lb4368** [comment]
Done.  Thanks @StevTheDev !

**Comment by StevTheDev** [comment]
These PS have been merged, which brings us closer to completing this epic.

[Treasuremap Elasticsearch & Kibana](https://review.opendev.org/c/airship/treasuremap/+/792788)
[Add elasticsearch-exporter to our elastic-stack](https://review.opendev.org/c/airship/treasuremap/+/792835)

I have a few PS still outstanding which will help close this out:

- [Remove Minio Components from airship-core lma](https://review.opendev.org/c/airship/treasuremap/+/793202) Relates to #111 

- [Update lma in airship-core type](https://review.opendev.org/c/airship/treasuremap/+/793106) updates the phase structure for LMA - incorporating the system into the airship-core workload and workload-config phases

- [Add lma to multi-tenant reference site](https://review.opendev.org/c/airship/treasuremap/+/793068). This change incorporates the LMA composites in with the lma sub-cluster workload and workload-config phases. Also it adds the lma-infra composite to the target cluster, and configures it to send logs and metrics up to the lma-subcluster elasticsearch.

**Comment by StevTheDev** [comment]
Those last two patchsets were getting too big to be easily reviewed, so I broke them down into smaller pieces:

- [794370: Fix up validation errors from LMA functions](https://review.opendev.org/c/airship/treasuremap/+/794370)
- [793106: Update lma in airship-core type](https://review.opendev.org/c/airship/treasuremap/+/793106)
- [793068: Add LMA to multi-tenant type and reference site lma sub-cluster](https://review.opendev.org/c/airship/treasuremap/+/793068)
- [794394: Add LMA to multi-tenant target cluster](https://review.opendev.org/c/airship/treasuremap/+/794394)

These are all pending review now. T-Shirt size for this item could still be considered M, because most of the development is complete, or bumped up to L due to the scope involved.

**Comment by StevTheDev** [comment]
Most of the patchsets associated with this feature have merged, but some things are not quite right in the implementation of the replacement transformers:

- [799090: Fix typo in kind and fix replacement transformer](https://review.opendev.org/c/airship/treasuremap/+/799090) merged.
- [799749: Add some and fix other LMA Versions Replacements](https://review.opendev.org/c/airship/treasuremap/+/799749)

**Comment by ak3216** [comment]
@StevTheDev looks like those 2 patchsets merged (799090 & 799749). Can we close this issue now? Thanks.

**Comment by ak3216** [comment]
Closing per code merges.
