### ISSUE TITLE
Implement phase/plan validation changes in Treasuremap manifests

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#176]
https://github.com/airshipit/airshipctl/issues/563 has moved document validation into the airshipctl phases & plans. We need to do the manifest work in Treasuremap to leverage the validation changes made in Airshipctl.

**Comment by sirajyasin** [comment]
@ak3216 , is this impacted with a pinned version of airshipctl in treasuremap ? I had the same issue with uplift and trying to fix it.

**Comment by sirajyasin** [comment]
My observation for this issue:
@ak3216 
Treasuremap phase/plan/executors is inherited from airshipctl with specific patches. So plan list gives all plans of treasuremap's test-site as well as airshipctl's test-site. 
Because of this validate docs is failing trying to validate all plans listed.

Plan list (from treasuremap [test-site] config):
PhasePlan/deploy-aiship-core-gating
PhasePlan/deploy-gating
PhasePlan/iso

Approach:
1. Should we stop inheriting phase/executors/plan from airshipctl ?
2. Should we have patch to delete unwanted plans 
		https://review.opendev.org/c/airship/treasuremap/+/795703/16/manifests/type/airship-core/phases/patches/delete-deploy-gating.yaml

**Comment by ak3216** [comment]
@sirajyasin this was reported from downstream and I'm not sure what version is currently being pulled as they're trying to stay up to date with current code, so I'm not sure there's a pinned version right now, though ultimately, they will pin to v2.1. 

As far as approach, if we did #2, then we'd need patches for each type to remove the unwanted phases/plans, correct? That is, we would still inherit from airshipctl, but then just modify the list to remove the unwanted ones.

**Comment by mf4716** [comment]
Related PS merged 23 June 2021: https://review.opendev.org/c/airship/treasuremap/+/796930

@sirajyasin , @ak3216 , can this issue be closed, or more PSs planned?

**Comment by sirajyasin** [comment]
@mf4716 , one part of the issue is to fix the plan list to restrict it to site/type specific by overriding the same plan 'deploy-gating', instead of defining new plans for each site/type. The change for this is now merged.

However the new format of phase/plan based validation will be addressed as part of the uplift PS [0]
[0] https://review.opendev.org/c/airship/treasuremap/+/795703

**Comment by sirajyasin** [comment]
All sites in treasuremap are passing validate docs after the uplift [PS](https://review.opendev.org/c/airship/treasuremap/+/795703) is merged. This issue can be marked closed.

**Comment by ak3216** [comment]
Closing per above patchset merge
