### ISSUE TITLE
Update init-infra phases for CA Cert Manager replacements

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#191]
**Problem description**
During sub-cluster deployment, it was found that the CA Cert Manager image could not be replaced in the manifests for the init-infra phases. 

**Proposed change**
Review init-infra & init-infra-networking phases. Add replacements as needed for CA Cert Manager image.

**Comment by drewwalters96** [comment]
The replacements Treasuremap needs were [recently added to Treasuremap](https://github.com/airshipit/airshipctl/commit/64eee820929d15d3a8d54a35c7c7136328e87880). Because we [updated our airshipctl reference](https://github.com/airshipit/treasuremap/commit/0c63baf8890afa1e7d5cb974f5428bb18492438d), we have access to the replacements.

Verified that they are working now in the master branch, closing.
