### ISSUE TITLE
airshipctl to support integrating with host-config-operator to perform day 2 operations

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#41]
Need a mechanism to exercise Day 2 operations with host-config-operator defined in https://github.com/airshipit/hostconfig-operator/issues/1 (as well as other update/upgrade scenarios)

As an operator I would like airshipctl to support various day 2 operations & updates leveraging the host-config-operator through treasuremap.

Acceptance Criteria :
    1. Validate host-config-operator functions/activities can be integrated into site/type

**Comment by ak3216** [comment]
@sirajyasin can you start looking at this in context of http://github.com/airshipit/hostconfig-operator/issues/1 and how we'd integrate hostconfig-operator with treasuremap?

**Comment by drewwalters96** [comment]
This has been completed, but it causes the Treasuremap deployment job to fail at the end because the image has not published to Quay.io. Another issue has been created in the hostconfig-operator repository to care for that.

Closed in https://github.com/airshipit/treasuremap/commit/511a4b0850a1c8f39924571e6146347513580267
