### ISSUE TITLE
Create LMA-infra (Base Composite Phases)  in airshipctl/treasuremap

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#70]
As a developer I would like to create an airshipctl phase called LMA-Base Composite Phase.
This phase will do the following in case of Undercloud Cluster as well as Sub-Cluster.
	- Install the LMA-Base Composite
	- the phases will include the LMA CRs for Cluster Infrastructure components which include :  Flow,Output,Podmonitor,ServiceMonitor,PrometheusRules,AlertmanagerConfig,etc. 	

This issue combines the following issues :
- Create subcluster monitoring-base composite in airshipctl/treasuremap #66
- Create undercloud monitoring-base composite in airshipctl/treasuremap #65
- Create logging-operator composite in airshipit/treasuremap for subcluster #56

**Comment by StevTheDev** [comment]
/assign me

This change adds two phases to treasuremap:

- An lma-infra-init phase which deploys the logging and prometheus
operators (And their associated CRDs) into the lma-infra namespace
- An lma-infra phase which creates CRs in the environment to
configure instances of lma infrastructure.

Splitting this into two phases was required, since kustomize/airshipctl
rejects a CR object before the corresponding CRD exists in the cluster.
Therefore, we have an init phase which deploys the initial HelmReleases,
followed by a separate phase which creates the CRs.

https://review.opendev.org/c/airship/treasuremap/+/769096/4

**Comment by StevTheDev** [comment]
Hey @sb1975, the change for this has been merged! 🎉 

https://review.opendev.org/c/airship/treasuremap/+/769096
