### ISSUE TITLE
Check k8s conformance via periodic jobs

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/treasuremap#79]
Now that we have scripts in place to drive running the CNCF and Kube Bench  conformance tests against a docker-based Airship deployment, and an experimental zuul job to run them on-demand, we should follow up with job(s) that run the tests on an ongoing basis.

It needs to be determined whether the tests should run weekly, monthly, or with some other cadence
It needs to be determined where the tests should run
When the tests fails, it needs to be communicated effectively to the development team

Note: the work itself may not have a code impact to the treasuremap codebase, depending on where the developed jobs live.

This is a follow on to: https://github.com/airshipit/treasuremap/issues/25

**Comment by rkjain** [comment]
Hi, I can pick this one up. :)

**Comment by mf4716** [comment]
@rkjain - is there a status?  Open patch-set?

**Comment by rkjain** [comment]
The conformance tests are running for docker provider as periodic jobs (every day) in STL lab. 

https://jenkins.nc.opensource.att.com/job/conformance/job/capd_conformance/61/console

However, running  conformance tests for baremetal is still a WIP. Once they are done, we can also set them as periodic.

**Comment by rkjain** [comment]
@mf4716 - Since this user story talks about setting the conformance job as periodic, and does not mention the provider, may be we can close the issue (as this is already been done for docker provider).  We can continue working on #80 (running conformance for baremetal, and set them as periodic when they are ready )  On the progress of #80, I will check with Ratnopam on the latest update for the issue and add comments on #80.

**Comment by ak3216** [comment]
@mf4716 @mattmceuen if we're good with what Rishabh has posted, I can close this one out.

**Comment by mattmceuen** [comment]
Yep that sounds good @ak3216 , we can close it - the intent was to make what we already have get run periodically.  @rkjain 's plan of scheduling baremetal appropriately after it's ready is good.
