### ISSUE TITLE
Include k8s conformance testing in bare-metal deployment jobs

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/treasuremap#80]
Now that we have scripts in place to drive running the CNCF and Kube Bench  conformance tests against a docker-based Airship deployment, and an experimental zuul job to run them on-demand, we should follow up with job(s) that run the tests against a more complete bare-metal Airship setup.

This issue should piggyback on the WIP to create a bare-metal site definition which is exercised periodically (e.g. daily).  At minimum the (relatively quick) CNCF conformance testing should be run as part of every CI-driven bare metal deployment job, and it should be evaluated whether the (relatively slow) Kube Bench testing should be included in that job.

Note: the work itself may not have a code impact to the treasuremap codebase, depending on where the developed jobs live.

This is a follow on to: https://github.com/airshipit/treasuremap/issues/25

**Comment by eratnch** [comment]
Just wanted to mention that one of the prerequisites to run conformance is to have a kubernetes cluster with minimum 3 nodes (1 controlplane and 2 worker nodes).

My understanding is that currently bare metal supports 1 control plane and 1 worker node. 

I ran the treasuremap deployment scripts to deploy the test site.

```
sudo kubectl --kubeconfig /home/stack/.airship/kubeconfig --context target-cluster get machines -w

NAME                         PROVIDERID                                      PHASE
cluster-controlplane-tlh9z   metal3://7de2c4f2-d0ae-4b39-bf9f-3e6b4e344d85   Running
worker-1-c69dc5855-8jlqb     metal3://f07a909a-ab7e-4e53-b0be-9acd7b134a98   Running

```
Conformance test will not run unless bare-metal deployment supports minimum 3 nodes cluster.

**Comment by eratnch** [comment]
Please assign this issue to me.

**Comment by ak3216** [comment]
Blocked waiting on  stl3 baremetal deployment

**Comment by mf4716** [comment]
@eratnch - Ratnopam, are we close(r) to finishing?

**Comment by eratnch** [comment]
@mf4716, the conformance test job on bare-metal stl3 is created at https://jenkins.nc.opensource.att.com/job/conformance/job/conformance_bare_metal_stl3/.

However running the conformance test on stl3 cluster timed out and increasing the timeout didn't help.
There are some pod-security policies that sonobuoy creates while running the tests that are not getting cleaned up properly. 

Please check following issue for details: https://github.com/vmware-tanzu/sonobuoy/issues/979
https://github.com/kubernetes/kubernetes/issues/92601

On `capd`  target cluster we can delete the cluster using `kind delete`  command and recreate it(thus getting rid of all namespaces and policies with it); however with stl3 cluster, that's not straight forward (at least not without some complexity)

stl3 cluster health doesn't seem to be ok at this point. It has to be in a healthy state before running the conformance tests.
![image](https://user-images.githubusercontent.com/66561014/111212286-cc61ed80-85a5-11eb-923d-4f295bb2e351.png)

One option is to run conformance for now on a virtualized 3 node cluster using metal3 provider instead of running on stl3 manifests. Once stl3 is in a healthy state, we can try running the tests on it.

**Comment by eratnch** [comment]
The [Jenkins job](https://jenkins.nc.opensource.att.com/job/conformance/job/conformance_bare_metal_stl3/77/console) for Conformance tests on stl3 cluster is ready. Frequency of run is set to weekly. 

This issue can be closed.

**Comment by ak3216** [comment]
Closing per above comment.
