### ISSUE TITLE
Manifests for Ericsson lab deployment

### ISSUE THREAD

**Issue by eak13** [airshipit/treasuremap#91]
As the deployment engineer for the Ericsson lab site, I want to have manifests created for the successful deployments of the lab using Airship 2, so that an engineer can deploy the baremetal site.

**Comment by ak3216** [comment]
Initial baremetal deployment happening in the R2 lab. This will allow us to extend that to test different types and/or different baremetal scenarios, but is not required for the V2 GA.

**Comment by rkjain** [comment]
Hi, I will be happy to help out here, and then may be look at #92 as well :)

**Comment by ak3216** [comment]
@rkjain it's yours. Please comment in #92 as well so I can assign you.

**Comment by rkjain** [comment]
I have got one machine with 128G memory, 768G storage to test airshipctl. The rest of the lab still requires networking to be completed by jan erik in order for us to have a similar setup to STL-3 lab, and get the manifests in place. Till the lab is ready, I have atleast reached to the point where I am able to get a 2 node bare metal cluster running on the given machine. In the meantime, I will work on setting up Jenkins i.e #92, and may be edit the manifests to scale to a 3-node setup, so that it can also be used to  test #80 (bare metal conformance).

**Comment by rkjain** [comment]
Manifests were created, and deployment was successful with minor issues. I have created issues : #141 and #142  for them. I have also requested access to nordix github - https://github.com/Nordix? , where the manifests will be maintained. Once I have more information on the repo, I will  commit the changes,  and we can mark #91 as completed

**Comment by rkjain** [comment]
This can be closed. The manifests are here https://github.com/rkjain/Eric-Airship2-POD1

**Comment by eak13** [comment]
Closing per above
